zendframework/zend-expressive-helpers

- composer.json
- src/UrlHelper.php
- test/UrlHelperFactoryTest.php
- test/UrlHelperTest.php
This patch updates the code to use the `RouteResultObserverInterface` from zend-expressive-router 1.1.0, vs the one in zend-expressive (as yet unreleased). The change allows the following:
- Fewer dependencies (zend-expressive-router vs zend-expressive + zend-expressive-router + zend-expressive-template)
- No circular dependencies
- Simpler test (mock zend-expressive-router's `RouteResultSubjectInterface` instead of zend-expressive's `Application` class)
This keeps all functionality, making it backwards compatible with 1.0.
> Use route result observer/subject interfaces from zend-expressive-router

- README.md
- src/Exception/MissingSubjectException.php
- src/UrlHelperFactory.php
- src/UrlHelperMiddleware.php
- src/UrlHelperMiddlewareFactory.php
- test/UrlHelperFactoryTest.php
- test/UrlHelperMiddlewareFactoryTest.php
- test/UrlHelperMiddlewareTest.php
As noted in a [comment on a zend-expressive issue](https://github.com/zendframework/zend-expressive/issues/186#issuecomment-162941737), the current approach to registering the `UrlHelper` is not feasible, due to the following issues:
- In cases where the `UrlHelper` is pulled during creation of the `TemplateRendererInterface` instance, and a `TemplatedErrorHandler` (or derivative, such as the whoops error handler) is also used, a circular dependency occurs. This is due to the `UrlHelperFactory` also pulling the `Application` service (as the `TemplatedErrorHandler` instance is pulled inside the `ApplicationFactory`).
- In cases where the `UrlHelper` creation is delayed until first use (e.g., in zend-expressive-zendviewrenderer's `url` helper factory), the helper is created *after* route …
> Implement UrlHelper middleware

- src/BodyParamsMiddleware.php
- test/BodyParamsMiddlewareTest.php
@weierophinney this should be a good start for what [we discussed](https://twitter.com/mwop/status/675377832684486656) last week. I just copied what you had, tweaked the namespace/class name, added comments, and added tests.
I'm not entirely sure what you meant by "attaching other strategies" in your follow-up tweet, though. If you can give me an example, we can work it in, but it certainly fits the need in my project as-is.
> BodyParams middleware stolen w/permission from mwop.net 

- src/UrlHelper.php
- test/UrlHelperTest.php
I believe that invoking helper should end in consistent results with generated urls containing - if set - the basePath prefix.
Should we also avoid getter (getRouteResult, getBasePath) calls and use $this->result and $this->basePath directly? 
(code contained mixed getter and property call for result)
I don't see any reason why those getter should be eventually overridden in a child class to send something different from the internal properties themselves.
kind regards
> prepend basePath when autogenerating from route result

- src/BodyParams/BodyParamsMiddleware.php
- src/BodyParams/JsonStrategy.php
- src/Exception/MalformedRequestBodyException.php
- src/UrlHelper.php
- test/BodyParams/BodyParamsMiddlewareTest.php
- test/BodyParams/JsonStrategyTest.php
@weierophinney thoughts on this to address #12 ?
The `BodyParamsMiddleware` isn't really supposed to be aware of the internals of the `Strategy`, so it wouldn't make sense to check the resulting null parsed body to guess as to what happened. The strategy doesn't have access to the `Response` either, so we can't do anything with it there.
Best approach I could think of was an exception specifically for malformed request bodies which the `Strategy` classes could use to communicate with the middleware that invoked them.
Finally, since a simple `Bad Request` isn't terribly useful to describe what went wrong, I opted to use the output from `json_last_error_msg()`. I think this should be fine because the [json_last_error_msg](https://secure.php.net/manual/en/function.json-last-error.php#refsect1 …
> Respond with 400 on bad JSON input

- composer.json
- test/ServerUrlHelperTest.php
- test/UrlHelperTest.php
This PR brings the project to 100% unit test coverage.
I don't see any kind of minimum test coverage percentage requirement in this repo or in any of the other Expressive project repos, but now that 100% coverage has been reached, I don't see any reason why it couldn't be retained. Generally, well-written code is easy to test, and code being difficult to test is a smell, IMO, so I'd like to require 100% for future `zend-expressive-helpers` contributions (and require no reduction in existing coverage for other Expressive repos as I get to them).
Thoughts, @weierophinney ? If 👍, I'll add a check to `.travis.yml` for this and merge.
> Achieve 100% test coverage

- test/BodyParams/JsonStrategyTest.php
Most downstream distribution use (with PHP 5) jsonc extension (instead of non-free json)
Only the error message is different, but the exception is properly raised.
This trivial patch allow the test suite to pass with both json and jsonc extensions.
> fix test suite with jsonc extension

- src/BodyParams/FormUrlEncodedStrategy.php
- test/BodyParams/BodyParamsMiddlewareTest.php
- test/BodyParams/FormUrlEncodedStrategyTest.php
I'm not sure why urlencoded requests weren't being parsed.
> Parsed form urlencoded requests.

- src/UrlHelper.php
- test/UrlHelperTest.php
Given a matched route with name `album.index` and path `/album[/page/{page:\d+}]`, invoking the `UrlHelper` with the route name `album.index` and no additional parameters while on page 5 would return `/album/page/5`, since it automatically merges existing params from the `RouteResult`. This behavior would make it impossible to use the `UrlHelper` to generate the base `/album` URL while on any page.
Invoking the helper with the new third argument `$reuseResultParams` set to `false` will now cause the helper to only take the params provided in the 2nd `$params` argument into consideration, which will produce the base `/album` URL in the above example.
BC Breaks:
- None if `UrlHelper` is being consumed directly.
- Method signature change if `UrlHelper` has been extended.
This addresses #10 , …
> Support generating default route w/o parameters

- src/BodyParams/BodyParamsMiddleware.php
MalformedRequestBodyException usage has been moved to JsonStrategy.
> Removes unused class use in BodyParamsMiddleware

- src/UrlHelper.php
- test/UrlHelperTest.php
This PR adds support for query parameters and fragments as discussed in zendframework/zend-expressive#325.
The invoke function has now this signature:
```php
public function __invoke($routeName = null, $params = [], $options = []);
```
- **$routeName**
Behaves exactly as it does now
- **$params**
Can have the following keys: `route`, `query`, `fragment`.
- `route` is an array containing the route parameters
- `query` appends query params
- `fragment` appends a fragment identifier, respectively
- **$options**
Can have the following keys: router, reuse_result_params.
- `router` must be an array containing the router options
- `reuse_result_params` is a boolean to indicate if the current RouteResult parameters will be used, defaults to true.
> Add query parameters and fragment support

- src/BodyParams/JsonStrategy.php
- test/BodyParams/JsonStrategyTest.php
`2.0.3` introduced an issue where a request along the lines of `PATCH /foo` with
`Content-Type: application/json` but no actual request body (since there may not
actually be any information to provide) would result in an exception. The
previous behavior was that the request would be allowed and the Parsed Body
would be NULL.
@weierophinney this pertains to what we discussed briefly via e-mail a while back.
Other possible alternatives would be to either require the user to use `text/plain` (or something else) as the content type when not needing to provide a request body in order for the `JsonStrategy` to not be executed (which would be a bit of a hassle if 100% of all other requests were `application/json`) *_OR_* to require the user to provide a valid empty JSON structure (`{}`, `'""'`, …
> Don't throw exception on empty JSON body

- .coveralls.yml
- .travis.yml
- CHANGELOG.md
- README.md
- composer.json
- src/UrlHelper.php
- test/UrlHelperTest.php
@weierophinney as is the case with [zend-expressive-helpers@2.0.0](https://github.com/zendframework/zend-expressive-router/pull/31), I'd greatly appreciate a sanity check on this before releasing `3.0.0`.
**Process after 👍 :**
1. Rebase to update `CHANGELOG.md` from e606699 to reflect what the actual release date will be.
2. Rebase with upstream/master and force-push the updated `master` to my fork (which will update this pull request).
3. Merge the pull request.
4. Tag `3.0.0` off of whatever the new commit hash for e606699 ends up being.
5. Follow the remaining release steps to bring develop into sync with master.
6. Delete the dev-3.0.0 branch.
End result should be that `3.0.0` is released, `develop` and `master` are in sync, `dev-3.0.0` is deleted, and there is no unreleased code in …
> 3.0.0 readiness check

- src/UrlHelper.php
- test/UrlHelperTest.php
Prior to this patch, `generate()` was setting the default argument for the `$fragment` argument to `''`, while `__invoke()` was setting it to `null`. The issue is that `''` is considered an invalid fragment, and `__invoke()` specifically tests for a `null` value before validating a fragment.
This patch updates the `generate()` signature to match that of `__invoke()`, solving the issue.
(Found when testing zendframework/zend-expressive-skeleton#54 against the new zend-expressive-helpers version.)
> Ensure that generate() default arguments match those of __invoke()

- test/BodyParams/BodyParamsMiddlewareTest.php
Creates an integration test to attempt to recreate the problem reported in zendframework/zend-expressive#371. It sets up the following conditions:
- A request method that can provide body content
- A request body with JSON content
- A `Content-Type` request header with the value `application/json;charset=utf-8`
It then passes the request to the `BodyParams` middleware, and validates that the request received by the delegate has the parsed contents.
Unfortunately... it does not validate the issue reported, as the test passes.
> Test to cover zendframework/zend-expressive#371

- README.md
- src/ContentLengthMiddleware.php
- test/ContentLengthMiddlewareTest.php
This feature is pulled from zend-diactoros' `SapiEmitterTrait::injectContentLength() method; a future version will omit that functionality, in favor of using this new middleware.
This middleware will inject a `Content-Length` response header based on the body size if:
- no `Content-Length` header is already present AND
- the body size is non-null
Otherwise, it returns the response verbatim.
> Adds a ContentLengthMiddleware for auto-injecting the Content-Length response header

- composer.json
- composer.lock
- src/BodyParams/BodyParamsMiddleware.php
- src/ContentLengthMiddleware.php
- src/ServerUrlMiddleware.php
- src/UrlHelperMiddleware.php
- test/BodyParams/BodyParamsMiddlewareTest.php
- test/ContentLengthMiddlewareTest.php
- test/ServerUrlMiddlewareTest.php
- test/UrlHelperMiddlewareTest.php
We keep also support for previosu version. It is accomplished by `webimpress/http-middleware-compatibility` repository, which allow to use any version of http-middleware. Consumer of the library can decide what version of http-middleware to use, and can easily migrate to the latest version at any time.
**Requires https://github.com/zendframework/zend-expressive-router/pull/36 to be merged before and released. Then `composer.json` in this PR should be updated.**
> Added support for `http-interop/http-middleware` 0.5.0 (No BC Break)

- src/UrlHelper.php
We don't need to have nullable typehints with parameters with "null" as default value
> Updated typehints - nullable typehints with default null

- CHANGELOG.md
It is fixed already in release notes: https://github.com/zendframework/zend-expressive-helpers/releases/tag/2.2.0
> Fixed link to PR in CHANGELOG

- CHANGELOG.md
- src/UrlHelperFactory.php
- src/UrlHelperMiddlewareFactory.php
- test/UrlHelperFactoryTest.php
- test/UrlHelperMiddlewareFactoryTest.php
When creating path-segregated middleware, you may want to provide middleware-specific routing. Once you do that, however, you need a new `UrlHelper` instance that contains that new router, and which knows the base path to prepend, if you want to generate route-specific URIs.
This patch is the first of several that accommodates this scenario.
The approach it uses is to allow optional constructor arguments to each of the `UrlHelperFactory` and `UrlHelperMiddlewareFactory`. Usage is as follows:
```php
// in a ConfigProvider or config file:
namespace Api;
use Zend\Expressive\Helper\UrlHelperFactory;
use Zend\Expressive\Helper\UrlHelperMiddlewareFactory;
use Zend\Expressive\Router\FastRouteRouter;
return [
'dependencies' => [
'factories' => [
Router::class => FastRouteRouter::class, …
```
> Allow varying `UrlHelper` for path-segregated middleware

- src/UrlHelper.php
- test/UrlHelperTest.php
I would like to offer a `RouteResult` object as a view helper, in order to get the matched route name and params. The usage of getRouteResult as public method simplify the implementation of such view helper.
> WIP: changed UrlHelper::getRouteResult in public for usage as view helper

- CHANGELOG.md
- README.md
- src/ConfigProvider.php
- src/Template/RouteTemplateVariableMiddleware.php
- src/Template/TemplateVariableContainer.php
- src/Template/TemplateVariableContainerMiddleware.php
- test/Template/RouteTemplateVariableMiddlewareTest.php
- test/Template/TemplateVariableContainerMiddlewareTest.php
- test/Template/TemplateVariableContainerTest.php
`TemplateRendererInterface::addDefaultParam()` has side-effects, and should not be used in async environments unless setting template variables that will be used on **every** request.
As such, this patch introduces an alternative workflow for aggregating pipeline-specific template variables. It provides two classes:
- `Zend\Expressive\Helper\Template\TemplateVariableContainer`, which provides a way to aggregate template variables, as well as merge local variables for the purpose of producing a set to pass to the template renderer.
- `Zend\Expressive\Helper\Template\TemplateVariableContainerMiddleware`, which provides a way to register the container as a request attribute within your pipeline.
Middleware can then set template parameters using either the container's `set()` or `merge()` …
> Provide stateless template variable aggregation
